# Generated by Django 5.2.14 on 2026-05-27 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (0, "Не сдано"),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("lab", "Лабораторная работа"),
                            ("practice", "Практическая работа"),
                            ("control", "Контрольная работа"),
                            ("exam", "Экзамен"),
                            ("credit", "Зачёт"),
                            ("homework", "Домашнее задание"),
                            ("coursework", "Курсовая работа"),
                        ],
                        max_length=20,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата выставления"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто поставил",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="accounts.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="accounts.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-created_at"],
                "unique_together": {("student", "subject", "grade_type")},
            },
        ),
        migrations.CreateModel(
            name="SemesterGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        verbose_name="Итоговая оценка",
                    ),
                ),
                ("semester", models.IntegerField(verbose_name="Семестр")),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="Учебный год"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_grades",
                        to="accounts.studentprofile",
                        verbose_name="Студент",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_grades",
                        to="accounts.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Итоговая оценка",
                "verbose_name_plural": "Итоговые оценки",
                "unique_together": {
                    ("student", "subject", "semester", "academic_year")
                },
            },
        ),
    ]
